"""
global_importance.py — CLI for Global SHAP Feature Importance.

Loads trained model artifacts and computes mean |SHAP| per feature
across a test set, producing a ranked importance table and plot.

Usage:
    python explainability/global_importance.py
    python explainability/global_importance.py \
        --artifacts-dir model/artifacts \
        --data-dir data/raw \
        --output-dir model/artifacts/shap \
        --max-samples 2000
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import click
import joblib
import numpy as np
import pandas as pd
from loguru import logger

sys.path.insert(0, str(Path(__file__).parent.parent))


@click.command()
@click.option("--artifacts-dir", default="model/artifacts",
              help="Directory containing rf_model.pkl, scaler.pkl, etc.")
@click.option("--data-dir", default=None,
              help="Real data directory (CIC-DDoS2019 CSVs). "
                   "If omitted, uses saved X_test.npy from artifacts.")
@click.option("--output-dir", default="model/artifacts/shap",
              help="Output directory for SHAP results and plots.")
@click.option("--max-samples", default=2000, type=int,
              help="Maximum samples for SHAP computation (memory guard).")
@click.option("--top-n", default=20, type=int,
              help="Number of top features to display in plot.")
def compute_global_importance(
    artifacts_dir: str,
    data_dir: str | None,
    output_dir: str,
    max_samples: int,
    top_n: int,
) -> None:
    """Compute and save global SHAP feature importance."""
    artifacts_path = Path(artifacts_dir)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Load model artifacts
    logger.info(f"Loading artifacts from {artifacts_path}...")
    clf = joblib.load(artifacts_path / "rf_model.pkl")
    scaler = joblib.load(artifacts_path / "scaler.pkl")

    with open(artifacts_path / "feature_names.json") as f:
        feature_names = json.load(f)

    # Load test data
    test_npy = artifacts_path / "X_test.npy"
    if test_npy.exists():
        logger.info("Loading saved test split from X_test.npy...")
        X_test = np.load(test_npy)
        logger.info(f"Test set shape: {X_test.shape}")
    elif data_dir is not None:
        logger.info(f"Loading real data from {data_dir}...")
        from model.train import load_real_data
        from sklearn.model_selection import train_test_split
        X_all, y_all, _ = load_real_data(data_dir)
        _, X_test_raw, _, _ = train_test_split(
            X_all, y_all, test_size=0.30, stratify=y_all, random_state=42
        )
        X_test = scaler.transform(X_test_raw)
    else:
        logger.error(
            "No data source available. Either provide --data-dir or ensure "
            "model/artifacts/X_test.npy exists (generated by model/train.py)."
        )
        sys.exit(1)

    # Subsample
    if len(X_test) > max_samples:
        rng = np.random.RandomState(42)
        idx = rng.choice(len(X_test), max_samples, replace=False)
        X_test = X_test[idx]
        logger.info(f"Subsampled to {max_samples} for SHAP computation.")

    # Compute SHAP
    try:
        import shap
        logger.info("Initializing TreeSHAP explainer...")
        explainer = shap.TreeExplainer(clf)
        shap_values = explainer.shap_values(X_test)

        if isinstance(shap_values, list) and len(shap_values) > 1:
            # Multi-class: average over DDoS classes (exclude class 0 = Benign)
            mean_abs = np.mean(
                [np.abs(shap_values[i]).mean(axis=0) for i in range(1, len(shap_values))],
                axis=0,
            )
        else:
            mean_abs = np.abs(np.array(shap_values)).mean(axis=0)

        importance_df = pd.DataFrame({
            "feature": feature_names[:len(mean_abs)],
            "mean_abs_shap": mean_abs,
        }).sort_values("mean_abs_shap", ascending=False)

        # Save CSV
        csv_path = output_path / "global_shap_importance.csv"
        importance_df.to_csv(csv_path, index=False)
        logger.info(f"SHAP importance saved to {csv_path}")

        # Save plot
        from explainability.visualizations import plot_global_importance
        plot_global_importance(
            dict(zip(importance_df["feature"], importance_df["mean_abs_shap"])),
            output_path=str(output_path / "global_shap_importance.png"),
            top_n=top_n,
        )

        # Print top features
        logger.info(f"\nTop {min(top_n, len(importance_df))} features:")
        logger.info(importance_df.head(top_n).to_string(index=False))

        # Entropy feature contribution
        ent_mask = importance_df["feature"].str.startswith("H_")
        ent_total = importance_df.loc[ent_mask, "mean_abs_shap"].sum()
        total = importance_df["mean_abs_shap"].sum()
        logger.info(
            f"\nEntropy features (H_*): {ent_total:.4f} / {total:.4f} "
            f"= {ent_total/total*100:.2f}% of total SHAP weight"
        )

    except ImportError:
        logger.error("SHAP not installed. Run: pip install shap")
        sys.exit(1)


if __name__ == "__main__":
    compute_global_importance()
